services:
  db:
    image: postgres:16.9
    environment:
      POSTGRES_DB: tareas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123!
    volumes:
      - pg-data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_NAME: tareas
      DB_USER: postgres
      DB_PASS: password123!
    depends_on:
      - db

volumes:
  pg-data:
