apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: practica-k8s
  region: us-east-1

iam:
  serviceRoleARN: arn:aws:iam::<ACCOUNT_ID>:role/LabRole

managedNodeGroups:
  - name: workers
    instanceType: t3.medium
    minSize: 1
    maxSize: 3
    desiredCapacity: 2
    iam:
      instanceRoleARN: arn:aws:iam::<ACCOUNT_ID>:role/LabRole
