apiVersion: v1
kind: Service
metadata:
  name: # nombre del servicio
spec:
  type: NodePort
  selector:
    app: # debe coincidir con el label del Deployment
  ports:
    - port: 80
      targetPort: # puerto en el que escucha la app (containerPort)
      nodePort: 30080
